theme: jekyll-theme-minimal
title: Minimal theme
logo: https://github.com/thesunnysideup/secondtimesthecharm/blob/gh-pages/assets/img/_logo.png
description: Testing text is fun
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
